//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomina
    {
        public int Id_Nom { get; set; }
        public Nullable<int> Año { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Monto_Total { get; set; }
    }
}
