//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomina
    {
        public int Id_Nom { get; set; }
        public Nullable<int> Año { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Monto_Total { get; set; }
    }
}
