//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Empleados
    {
        public int Id_Sal { get; set; }
        public string Tipo_Salida { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> Fecha_salida { get; set; }
        public Nullable<int> Id_Em { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
