//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Empleados
    {
        public int Id_Sal { get; set; }
        public string Tipo_Salida { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> Fecha_salida { get; set; }
        public Nullable<int> Id_Em { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
